# -*- coding: utf-8 -*-
"""trend_linchart.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u0U9dOmaaBN6GIbC-K19tDhp8gwOYmCy
"""

from pandas import datetime
from sklearn.linear_model import LinearRegression
from matplotlib import pyplot
import numpy 
 
def parser(x):
	return datetime.strptime(+x, '%Y-%m')
 
# fit linear model
X = [i for i in range(0, len(data['Adj Close']))]
X = numpy.reshape(X, (len(X), 1))
y = data['Adj Close'].values
model = LinearRegression()
model.fit(X, y)
# calculate trend
trend = model.predict(X)
# plot trend
pyplot.plot(y)
pyplot.plot(trend)
pyplot.show()
# detrend
detrended = [y[i]-trend[i] for i in range(0, len(data))]
# plot detrended
pyplot.plot(detrended)
pyplot.show()